name: ghapi
on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ghapi:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: pip install ghapi

      - name: make a comment
        run: python ghapi.py
        env:
          NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
