name: ghapi
on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ghapi:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository Contents
        uses: actions/checkout@main

      # - name: install dependencies
      #   run: pip install ghapi

      - name: make a comment
        run: |
          pip install ghapi
          python ghapi.py
        env:
          NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
