name: project-assignment-wandb
on: issue_comment

permissions:
  contents: read
  issues: write
  pull-requests: write


jobs:
  project-assignment:
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')
    runs-on: ubuntu-latest
    steps:
      - name: fetch repo contents
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install ghapi wandb

      - name: get run id
        id: run-id-value
        shell: python
        run: |
          import re, os
          comment = os.getenv('PR_COMMENT', '')
          match = re.search('/wandb[\s+](\S+)', comment)

          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            if match:
              printf(f'VAL_FOUND=true', file=f)
              printf(f'RUN_ID={match.group(1)}', file=f)

            else:
              printf(f'VAL_FOUND=false', file=f)
        env:
          PR_COMMENT: ${{ github.event.comment.body }}

      - name: make comparison report
        if: steps.run-id-value.outputs.VAL_FOUND == 'true'
        id: wandb-report
        run: python comparison_report.py
        env:
          WANDB_ENTITY: vck281000
          WANDB_PROJECT: mlops-course-001
          BASELINE_TAG: baseline
          RUN_ID: "${{ steps.run-id-value.outputs.RUN_ID }}"
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: make a comment
        uses: actions/github-script@v6
        if: steps.wandb-report.outcome == 'success'
        with:
          script: |
            var msg = `Comparison report is available [here](${process.env.REPORT_URL})`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
        env:
          REPORT_URL: "${{ steps.wandb-report.outputs.REPORT_URL }}"
